export const NOTIFICATION_STATUS = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
};

export const NOTIFICATION_STATUS_VALUES = Object.values(NOTIFICATION_STATUS);

export const DEFAULT_STATUS = NOTIFICATION_STATUS.PENDING;
