export const INSPECTION_STATUS = {
  PENDING: 'PENDING',
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const INSPECTION_STATUS_VALUES = Object.values(INSPECTION_STATUS);

export const DEFAULT_STATUS = INSPECTION_STATUS.PENDING;
