export const EXTINGUISHER_STATUS = {
  ACTIVE: 'ACTIVE',
  INSPECTION_DUE: 'INSPECTION_DUE',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  EXPIRED: 'EXPIRED',
  RETIRED: 'RETIRED',
};

export const EXTINGUISHER_STATUS_VALUES = Object.values(EXTINGUISHER_STATUS);

export const DEFAULT_STATUS = EXTINGUISHER_STATUS.ACTIVE;
